"BIN:EOLor version 1"

diff --git a/Bin/test/run_cmd b/Bin/test/run_cmd
--- a/Bin/test/run_cmd
+++ b/Bin/test/run_cmd
@@ -1,8 +1,8 @@
-#!/bin/sh
-
-if type "$1" >/dev/null 2>&1; then
-  eval "$*"
-else
-  printf "Command not found: %s" "$1"
-  exit 1
+#!/bin/sh
+
+if type "$1" >/dev/null 2>&1; then
+  eval "$*"
+else
+  printf "Command not found: %s" "$1"
+  exit 1
 fi
diff --git a/Test/bin/test_Filter b/Test/bin/test_Filter
--- a/Test/bin/test_Filter
+++ b/Test/bin/test_Filter
@@ -1,84 +1,1 @@
-#!/bin/sh
-
-__check_err__() {
-	error_code="$?"
-	[ "$error_code" -ne 0 ] && printf "Error of %d\n\n" "$error_code"
-}
-
-echo "
-#>######################################<#
-##################| CMD |#################
-#>######################################<#
-
-$(
-	filtrate \
-		--info hostnamectl \
-		--filter "host" \
-		--delim ":"
-	__check_err__
-)
-
-#>######################################<#
-#################| FILE |################
-#>######################################<#
-
-$(
-	filtrate \
-		--info /home/qc/Dotfiles/Test/env/hostnamectl \
-		--filter "host" \
-		--delim ":"
-	__check_err__
-	# bat /home/qc/Dotfiles/hostnamectl
-)
-
-#>######################################<#
-##################| DIR |#################
-#>######################################<#
-
-$(
-	filtrate \
-		--info "/home/qc/Dotfiles/Test/env" \
-		--filter "host" \
-		--delim ":"
-	__check_err__
-	# bat /home/qc/Dotfiles/hostnamectl
-)
-
-#>######################################<#
-#################| INFO |################
-#>######################################<#
-
-$(
-	filtrate \
-		--info hostnamectls \
-		--filter "host" \
-		--delim ":"
-	__check_err__
-)
-
-
-#>######################################<#
-################| NO INFO |###############
-#>######################################<#
-$(
-	filtrate hostnamectl --filter "host"
-	__check_err__
-)
-
-#>######################################<#
-###################| RG |#################
-#>######################################<#
-
-$(
-	hostnamectl | rg "host"
-	hostnamectl | rg "host" | sd "^.*:\s" ''
-	__check_err__
-)
-"
-
-# how_fast_is \
-# 	'filtrate \
-# 	--info hostnamectl \
-# 	--filter "host" \
-# 	--delim ":"' \
-# 	'weHave hostnamectl && weHave rg && weHave sd hostnamectl | rg "host" | sd "^.*:\s" '''
+#!/bin/sh__check_err__() {	error_code="$?"	[ "$error_code" -ne 0 ] && printf "Error of %d\n\n" "$error_code"}echo "#>######################################<###################| CMD |##################>######################################<#$(	filtrate \		--info hostnamectl \		--filter "host" \		--delim ":"	__check_err__)#>######################################<##################| FILE |#################>######################################<#$(	filtrate \		--info /home/qc/Dotfiles/Test/env/hostnamectl \		--filter "host" \		--delim ":"	__check_err__	# bat /home/qc/Dotfiles/hostnamectl)#>######################################<###################| DIR |##################>######################################<#$(	filtrate \		--info "/home/qc/Dotfiles/Test/env" \		--filter "host" \		--delim ":"	__check_err__	# bat /home/qc/Dotfiles/hostnamectl)#>######################################<##################| INFO |#################>######################################<#$(	filtrate \		--info hostnamectls \		--filter "host" \		--delim ":"	__check_err__)#>######################################<#################| NO INFO |################>######################################<#$(	filtrate hostnamectl --filter "host"	__check_err__)#>######################################<####################| RG |##################>######################################<#$(	hostnamectl | rg "host"	hostnamectl | rg "host" | sd "^.*:\s" ''	__check_err__)"# how_fast_is \# 	'filtrate \# 	--info hostnamectl \# 	--filter "host" \# 	--delim ":"' \# 	'weHave hostnamectl && weHave rg && weHave sd hostnamectl | rg "host" | sd "^.*:\s" '''
