working on the nixos scripts

diff --git a/Scripts/validate_email b/Scripts/validate_email
--- a/Scripts/validate_email
+++ b/Scripts/validate_email
@@ -1,87 +1,171 @@
 #!/bin/sh
 
-SCR_NAME="validate_email"
+scr_name="validate_email"
 label="Email"
+exit_on_error=true
 
 show_usage_guide() {
-  printf "\n\nUsage: %s <email>\n\n" "$SCR_NAME"
-  printf "Examples:\n"
-  printf "  %s john.doe@example.com\n" "$SCR_NAME"
-  printf "  %s jane.doe@\n" "$SCR_NAME"
-  printf "  %s @example.com\n" "$SCR_NAME"
-  printf "  %s invalid.email\n" "$SCR_NAME"
+  printf "\n\nUsage: %s <email>\n\n" "$scr_name"
 }
 
 parse_arguments() {
   case "$1" in
-  -h | --help) show_usage_guide ;;
-  "") pOut --missing "$label" ;;
-  -*) pOut --ivalid "Option" "$1" ;;
+  -h | --help)
+    show_usage_guide
+    exit 0
+    ;;
+  -t | --test)
+    run_tests
+    exit 0
+    ;;
+  "") pout --missing "$label" ;;
+  -*) pout --invalid "Option" "$1" ;;
   *) email="$1" ;;
   esac
 }
 
 split_email_on_at() {
-  #@ Check if the email contains an @ sign
-  printf '%s' "$email" | grep -q '@' || {
-    pOut "--invalid $label" "Missing the @ sign" "$email"
-  }
+  # Check if the email contains an @ sign
+  printf '%s' "$email" | grep -q '@' || return 1
 
-  #@ Split the email into username and domain parts
-  username=$(printf '%s' "$email" | cut -d '@' -f 1)
-  domain=$(printf '%s' "$email" | cut -d '@' -f 2)
+  # Split the email into username and domain parts
+  username="${email%%@*}"
+  domain="${email#*@}"
 }
 
 check_username() {
-  #@ Check if the username is empty
-  if [ -z "$username" ]; then
-    pOut "--invalid $label" "Missing the username" "$email"
-  fi
+  # Check if the username is empty
+  [ "$username" ] || return 1
+  # pout "--invalid $label" "Missing the username" "$email"
+  #   return 1
 }
 
 check_domain() {
-  domain_name() {
-    [ "$domain" ] ||
-      pOut "--invalid $label" "Missing the domain" "$email"
-  }
 
-  domain_dot() {
-    printf '%s' "$domain" | grep -q '\.' ||
-      pOut "--invalid $label" "Missing the '.' in the domain" "$email"
-  }
+  tld_regex='^[a-zA-Z]+$'
 
-  tld() {
-    tld_regex='^[a-zA-Z]+$'
+  # Extract the top-level domain from the domain
+  tld="${domain##*.}"
 
-    #@ Extract the top-level domain from the domain
-    tld=$(printf "%s" "$domain" | awk -F. '{print $NF}')
+  if [ -z "$domain" ]; then
+    # pout "--invalid $label" "Missing the domain" "$email"
+    echo "DOM MISSING"
+    return 1
+  elif
+    printf '%s' "$domain" | grep -q '\.'
+  then
+    pout "--invalid $label" "Missing the '.' in the domain" "$email"
+  elif
 
-    #@ Check if the top-level domain is empty
-    [ "$tld" ] ||
-      pOut "--invalid $label" "Missing the top-level domain" "$email"
-
-    #@ Check if the top-level contains invalid characters
-    printf "%s" "$tld" | grep -Eq "$tld_regex" ||
-      pOut "--invalid $label" "Check characters in the top-level domain" "$email"
-  }
-
-  domain_name
-  domain_dot
-  tld
+    # Check if the top-level domain is empty
+    [ -z "$tld" ]
+  then
+    pout "--invalid $label" "Missing the top-level domain" "$email"
+  elif
+    # Check if the top-level contains invalid characters
+    printf "%s" "$tld" | grep -Eq "$tld_regex"
+  then
+    pout "--invalid $label" "Check characters in the top-level domain" "$email"
+  fi
 }
 
-pOut() {
-  pout "$@"
-  exit 1
+pout() {
+  if [ "$exit_on_error" = true ]; then
+    p0ut "$@"
+    exit 1
+  else
+    p0ut "$@"
+    printf "\n"
+  fi
 }
-main() {
-  parse_arguments "$@"
-  split_email_on_at
-  check_username
-  check_domain
+
+run_tests() {
+  #@ Define test emails
+  # "john.doeexample.com" # Missing @ sign
+  # "@example.com"        # Missing username
+  # "johndoe@"            # Missing domain
+  # "johndoe@example"     # Missing top-level domain
+  # "johndoe@example.123" # Invalid characters in top-level domain
+  # "johndoe@example.com" # Valid email address
+
+  emails="
+    john.doeexample.com
+    @example.com
+    johndoe@
+    johndoe@example
+    johndoe@example.123
+    johndoe@example.com
+  "
+
+  #@ Allow tests to continue in spite of errors
+  exit_on_error=false
+
+  # #@ Iterate over test cases
+  # for email in $test_emails; do
+  #   # printf "%s" "$test_case"
+  process
+  #   printf "\n"
+  # done
+}
+
+process() {
+  for email in $emails; do
+
+    # Check if the email contains an @ sign
+    if printf '%s' "$email" | grep -q '@'; then
+      # Split the email into username and domain parts
+      username="${email%%@*}"
+      domain="${email#*@}"
+    else
+      pout "--invalid $label" "Missing the @" "$email"
+      continue
+    fi
+
+    # printf "USER: %s DOMAIN:%s\n" "$username" "$domain"
+    [ "$username" ] || pout "--invalid $label" "Missing the username" "$email"
+
+    if [ "$domain" ]; then
+      tld_regex='^[a-zA-Z0-9-]+$' # Accept only letters, numbers and hyphens
+      tld="${domain##*.}" # Top-level domain
+
+      if ! printf '%s' "$domain" | grep -q '\.'; then
+        pout "--invalid $label" "Missing the domain extension" "$email"
+      elif ! printf "%s" "$tld" | grep -Eq "$tld_regex"; then
+        pout "--invalid $label" "Check characters in the domain extension" "$email"
+      fi
+    fi
+    # if split_email_on_at; then
+    #   echo " | has @"
+    #   # printf "%s" "$email"
+    #   if split_email_on_at; then
+    #     echo " | has @"
+    # printf "%s" "$email"
+    #   else
+    #     pout "--invalid $label" "Missing the @ sign" "$email"
+    #     echo
+    #     continue
+    #   fi
+    # else
+    #   pout "--invalid $label" "Missing the @ sign" "$email"
+    #   echo
+    #   continue
+    # fi
+  done
 
   #@ All checks passed, the email address is valid
+  # printf "%s" "$email"
+}
+
+main() {
+  #@ Accept cli arguments
+  parse_arguments "$@"
+
+  #@ Validate the email
+  process
+
+  #@ Return the validated email
   printf "%s" "$email"
+
 }
 
 main "$@"
